# A pipeline with three sequential jobs
# Output variables from previous jobs are being referred

jobs:
  - job: A
    pool: Hosted VS2017
    variables:
    - name: myVar
      value: InitialValue
    steps:
        - checkout: none
        - powershell: Write-Host 'Initial Variable value - ' + $(myVar)
          displayName: 'Run a script'
        - powershell: echo "##vso[task.setvariable variable=myVar;]NewValue"
        - powershell: echo "##vso[task.setvariable variable=myOutputVarA;isOutput=true]I was set in Job A"
          name: setoutputvar
          displayName: 'set output variable'
        - powershell: Write-Host 'Variable set in this job - ' + $(setoutputvar.myOutputVarA)
          displayName: 'Run a script'
        - powershell: Write-Host $(myVar)
  - job: B
    dependsOn: A
    pool: Hosted VS2017
    variables:
        myVarFromJobA: $[dependencies.A.outputs['setoutputvar.myOutputVarA']]
    steps:
        - powershell: echo "##vso[task.setvariable variable=myOutputVarB;isOutput=true]I was set in Job B"
          name: setoutputvar
          displayName: 'set output variable'
        - powershell: |
            Write-Host 'Variable obtained from Job A - $(myVarFromJobA)'
            Write-Host 'Variable set in this job - $(setoutputvar.myOutputVarB)'
          displayName: 'Print variables'
  - job: C
    dependsOn: B
    pool: Hosted VS2017
    variables:
        myVarFromJobA: $[dependencies.A.outputs['setoutputvar.myOutputVarA']]
        # myVarFromJobA would be empty as job C does not depend on job A
        myVarFromJobB: $[dependencies.B.outputs['setoutputvar.myOutputVarB']]
    steps:
        - powershell: |
            Write-Host "Accessing variables from dependent jobs"
            Write-Host 'Variable set in Job A says - $(myVarFromJobA)' 
            Write-Host 'Variable set on Job B says - $(myVarFromJobB)'
          displayName: 'Print variables'
